#!/bin/bash
cd "$HOME"

echo "Init submodules"
yadm submodule update --recursive --init

installing vim plugins, should do later with dein
#if command -v vim >/dev/null 2>&1; then
#  echo "Bootstraping Vim"
#  vim '+PlugUpdate' '+PlugClean!' '+PlugUpdate' '+qall'
#fi
